name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy mỗi ngày lúc 00:00 UTC (7h sáng VN)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README
        run: |
          echo "Last update: $(date)" > README.md

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Daily commit" || echo "No changes to commit"
          git push
